<br>

# Transform

In [1]:
import pandas as pd

from tjsp_unidades import extract
from tjsp_unidades.transform.small_functions import adjust_columns

<br>

---

## Get Data

<br>

---

### Quem Somos

In [2]:
quem_somos = extract.QuemSomos()

quem_somos.rajs.head()

,id_raj,raj_nome,raj_sigla,raj_regiao,juiz_diretor_nome,juiz_diretor_email
0,1,1ª RAJ - Grande São Paulo,1ª RAJ,Grande São Paulo,Fernando Antonio Tasso,daraj1@tjsp.jus.br
1,2,2ª RAJ - Araçatuba,2ª RAJ,Araçatuba,Antonio Fernando Sanches Batagelo,daraj2@tjsp.jus.br
2,3,3ª RAJ - Bauru,3ª RAJ,Bauru,Gilmar Ferraz Garmes,daraj3@tjsp.jus.br
3,4,4ª RAJ - Campinas,4ª RAJ,Campinas,Nelson Augusto Bernardes de Souza,daraj4@tjsp.jus.br
4,5,5ª RAJ - Presidente Prudente,5ª RAJ,Presidente Prudente,José Wagner Parrão Molina,daraj5@tjsp.jus.br

In [3]:
quem_somos.cjs.head()

   id_cj cj_sigla                      cj_nome  id_raj
0      0  Capital                      Capital       1
1      1    1ª CJ  1ª Circunscrição Judiciária       7
2      2    2ª CJ  2ª Circunscrição Judiciária       1
3      3    3ª CJ  3ª Circunscrição Judiciária       1
4      4    4ª CJ  4ª Circunscrição Judiciária       1

In [4]:
quem_somos.comarcas

São 321 comarcas

    comarca_tjsp  id_cj
0     Adamantina     30
1          Aguaí     50
2         Agudos     32
3    Altinópolis     39
4      Americana     53
..           ...    ...
316  Vila Mimosa      8
317      Vinhedo      5
318    Viradouro     14
319   Votorantim     19
320  Votuporanga     17

[321 rows x 2 columns]

<br>

---

### Municípios

In [5]:
listar_municipios = extract.ListarMunicipios()

# Obtem todos os IDs dos Municípios do TJSP
df_municipios = listar_municipios.request()

São 4267 termos para pesquisa

In [6]:
# Results
df_municipios.info()
df_municipios.head()

<class 'pandas.DataFrame'>
RangeIndex: 645 entries, 0 to 644
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_municipio_ibge         645 non-null    int64
 1   id_municipio_tjsp         645 non-null    int64
 2   municipio_tjsp            645 non-null    str
 3   municipio_tjsp_corrigido  645 non-null    str
dtypes: int64(2), str(2)
memory usage: 20.3 KB

,id_municipio_ibge,id_municipio_tjsp,municipio_tjsp,municipio_tjsp_corrigido
0,3500105,6504,Adamantina,Adamantina
1,3500204,6505,Adolfo,Adolfo
2,3500303,6506,Aguaí,Aguaí
3,3500402,6507,Águas da Prata,Águas da Prata
4,3500501,6508,Águas de Lindóia,Águas de Lindóia

<br>

---

### Unidades

In [7]:
listar_unidades = extract.ListarUnidades()

df_unidades = listar_unidades.get_unidades_batch(
    list_id_tjsp=list(df_municipios["id_municipio_tjsp"]),
)

df_unidades.head()

,id_municipio_tjsp,raj,municipio_tjsp,comarca_tjsp,comarca_sede,imoveis
0,6507,4ª RAJ Campinas,Águas da Prata,São João da Boa Vista,0,Cartório Anexo do Juizado Especial Cível - UNI...
1,6507,4ª RAJ Campinas,Águas da Prata,São João da Boa Vista,0,Fórum I Dr. Plínio Barreto
2,6512,10ª RAJ Sorocaba,Alambari,Itapetininga,0,Fórum Itapetininga I - (Desembargador Bernarde...
3,6512,10ª RAJ Sorocaba,Alambari,Itapetininga,0,Fórum Itapetininga II (Criminal) Juiz Paulo Ru...
4,6516,2ª RAJ Araçatuba,Alto Alegre,Penápolis,0,Fórum Penápolis I -

<br>

---

## Tratamento

In [8]:
# Merge
df_unidades_merge = pd.merge(
    left=df_municipios,
    right=df_unidades,
    left_on="id_municipio_tjsp",
    right_on="id_municipio_tjsp",
    how="inner",
    suffixes=["", "_copy"],
)

df_unidades_merge = df_unidades_merge.drop(
    labels=["municipio_tjsp_copy"],
    axis="columns",
    errors="ignore",
)

# Unidades
df_unidades_merge.info()
df_unidades_merge.head()

<class 'pandas.DataFrame'>
RangeIndex: 1310 entries, 0 to 1309
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_municipio_ibge         1310 non-null   int64
 1   id_municipio_tjsp         1310 non-null   int64
 2   municipio_tjsp            1310 non-null   str
 3   municipio_tjsp_corrigido  1310 non-null   str
 4   raj                       1310 non-null   str
 5   comarca_tjsp              1310 non-null   str
 6   comarca_sede              1310 non-null   int64
 7   imoveis                   1310 non-null   str
dtypes: int64(3), str(5)
memory usage: 82.0 KB

,id_municipio_ibge,id_municipio_tjsp,municipio_tjsp,municipio_tjsp_corrigido,raj,comarca_tjsp,comarca_sede,imoveis
0,3500105,6504,Adamantina,Adamantina,5ª RAJ Presidente Prudente,Adamantina,1,Fórum I Adamantina
1,3500105,6504,Adamantina,Adamantina,5ª RAJ Presidente Prudente,Adamantina,1,Fórum II Adamantina (Residência Oficial)
2,3500105,6504,Adamantina,Adamantina,5ª RAJ Presidente Prudente,Adamantina,1,Fórum III Adamantina - UAAJ - FAC. ADAM. INTEG...
3,3500204,6505,Adolfo,Adolfo,8ª RAJ São José do Rio Preto,José Bonifácio,0,Fórum José Bonifácio - II (CEJUSC)
4,3500204,6505,Adolfo,Adolfo,8ª RAJ São José do Rio Preto,José Bonifácio,0,Fórum José Bonifácio I (Principal)

<br>

---

### Comarcas

In [9]:
df_tjsp = df_unidades_merge.copy()

# Comarca
df_tjsp_com = df_tjsp[df_tjsp["comarca_sede"] == 1]

# Filtra Colunas
df_tjsp_com = df_tjsp_com.drop(
    labels=[
        "comarca_sede",
        "unidades",
        "raj",
    ],
    axis="columns",
    errors="ignore",
)

# Deleta Duplicados
df_tjsp_com = df_tjsp_com.drop_duplicates()

# Renomeia Colunas
df_tjsp_com = df_tjsp_com.rename(
    {
        "municipio_tjsp_corrigido": "comarca_tjsp_corrigido",
        "id_municipio_ibge": "id_comarca",
    },
    axis="columns",
)

# Deleta
df_tjsp_com = df_tjsp_com.drop(
    labels=["municipio_tjsp"],
    axis="columns",
    errors="ignore",
)

# Bata Bater
df_tjsp_com = adjust_columns(
    df=df_tjsp_com,
    column_ajust="comarca_tjsp",
)

df_tjsp_com.info()
df_tjsp_com.head()

<class 'pandas.DataFrame'>
Index: 630 entries, 0 to 1308
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_comarca              630 non-null    int64
 1   id_municipio_tjsp       630 non-null    int64
 2   comarca_tjsp_corrigido  630 non-null    str
 3   comarca_tjsp            630 non-null    str
 4   imoveis                 630 non-null    str
 5   comarca_tjsp_temp       630 non-null    str
dtypes: int64(2), str(4)
memory usage: 34.5 KB

,id_comarca,id_municipio_tjsp,comarca_tjsp_corrigido,comarca_tjsp,imoveis,comarca_tjsp_temp
0,3500105,6504,Adamantina,Adamantina,Fórum I Adamantina,adamantina
1,3500105,6504,Adamantina,Adamantina,Fórum II Adamantina (Residência Oficial),adamantina
2,3500105,6504,Adamantina,Adamantina,Fórum III Adamantina - UAAJ - FAC. ADAM. INTEG...,adamantina
5,3500303,6506,Aguaí,Aguaí,Comarca de Aguaí,aguai
8,3500501,6508,Águas de Lindóia,Águas de Lindóia,Fórum Águas de Lindóia,aguas de lindoia

In [10]:
df_temp = adjust_columns(df=quem_somos.comarcas, column_ajust="comarca_tjsp")

São 321 comarcas

Usando `left` eu dropo a Vila Mimosa!

In [11]:
df_tjsp_com = pd.merge(
    left=df_tjsp_com,
    right=df_temp,
    left_on="comarca_tjsp_temp",
    right_on="comarca_tjsp_temp",
    how="left",
    suffixes=["", "_copy"],
)

# Deleta
df_tjsp_com = df_tjsp_com.drop(
    labels=["comarca_tjsp_copy"],
    axis="columns",
    errors="ignore",
)

# Ordena
df_tjsp_com = df_tjsp_com.iloc[
    df_tjsp_com["comarca_tjsp"].str.normalize("NFKD").argsort()
]

# Reset Index
df_tjsp_com = df_tjsp_com.reset_index(drop=True)

df_tjsp_com = df_tjsp_com.drop(
    labels=["comarca_tjsp_temp", "id_municipio_tjsp"],
    axis="columns",
)

# Reordena
df_tjsp_com = df_tjsp_com[
    [
        "id_comarca",
        "comarca_tjsp",
        "comarca_tjsp_corrigido",
        "id_cj",
    ]
]

df_temp = df_tjsp_com[df_tjsp_com["id_cj"].isna()]
if len(df_temp) > 0:
    raise Exception("Erro")

df_tjsp_com.info()
df_tjsp_com.head()

<class 'pandas.DataFrame'>
RangeIndex: 630 entries, 0 to 629
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_comarca              630 non-null    int64
 1   comarca_tjsp            630 non-null    str
 2   comarca_tjsp_corrigido  630 non-null    str
 3   id_cj                   630 non-null    int64
dtypes: int64(2), str(2)
memory usage: 19.8 KB

   id_comarca comarca_tjsp comarca_tjsp_corrigido  id_cj
0     3500105   Adamantina             Adamantina     30
1     3500105   Adamantina             Adamantina     30
2     3500105   Adamantina             Adamantina     30
3     3500303        Aguaí                  Aguaí     50
4     3500709       Agudos                 Agudos     32

<br>

---

### Municipios > Comarcas

In [12]:
# Filtra Colunas
df_municipios_fim = df_unidades_merge.drop(
    labels=[
        "unidades",
        "raj",
        #'id_municipio_tjsp'
    ],
    axis="columns",
    errors="ignore",
)

# Deleta Duplicados
df_municipios_fim = df_municipios_fim.drop_duplicates()

# Reset Index
df_municipios_fim = df_municipios_fim.reset_index(drop=True)

df_municipios_fim.info()
df_municipios_fim.head()

<class 'pandas.DataFrame'>
RangeIndex: 1306 entries, 0 to 1305
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_municipio_ibge         1306 non-null   int64
 1   id_municipio_tjsp         1306 non-null   int64
 2   municipio_tjsp            1306 non-null   str
 3   municipio_tjsp_corrigido  1306 non-null   str
 4   comarca_tjsp              1306 non-null   str
 5   comarca_sede              1306 non-null   int64
 6   imoveis                   1306 non-null   str
dtypes: int64(3), str(4)
memory usage: 71.6 KB

,id_municipio_ibge,id_municipio_tjsp,municipio_tjsp,municipio_tjsp_corrigido,comarca_tjsp,comarca_sede,imoveis
0,3500105,6504,Adamantina,Adamantina,Adamantina,1,Fórum I Adamantina
1,3500105,6504,Adamantina,Adamantina,Adamantina,1,Fórum II Adamantina (Residência Oficial)
2,3500105,6504,Adamantina,Adamantina,Adamantina,1,Fórum III Adamantina - UAAJ - FAC. ADAM. INTEG...
3,3500204,6505,Adolfo,Adolfo,José Bonifácio,0,Fórum José Bonifácio - II (CEJUSC)
4,3500204,6505,Adolfo,Adolfo,José Bonifácio,0,Fórum José Bonifácio I (Principal)

In [13]:
df_temp = adjust_columns(df=df_municipios_fim, column_ajust="comarca_tjsp")
df_temp.head()

,id_municipio_ibge,id_municipio_tjsp,municipio_tjsp,municipio_tjsp_corrigido,comarca_tjsp,comarca_sede,imoveis,comarca_tjsp_temp
0,3500105,6504,Adamantina,Adamantina,Adamantina,1,Fórum I Adamantina,adamantina
1,3500105,6504,Adamantina,Adamantina,Adamantina,1,Fórum II Adamantina (Residência Oficial),adamantina
2,3500105,6504,Adamantina,Adamantina,Adamantina,1,Fórum III Adamantina - UAAJ - FAC. ADAM. INTEG...,adamantina
3,3500204,6505,Adolfo,Adolfo,José Bonifácio,0,Fórum José Bonifácio - II (CEJUSC),jose bonifacio
4,3500204,6505,Adolfo,Adolfo,José Bonifácio,0,Fórum José Bonifácio I (Principal),jose bonifacio

In [14]:
df_temp2 = adjust_columns(df=df_tjsp_com, column_ajust="comarca_tjsp")

# Filtra Colunas
df_temp2 = df_temp2.drop(
    labels=[
        "comarca_tjsp",
        "comarca_tjsp_corrigido",
        "id_cj",
    ],
    axis="columns",
    errors="ignore",
)

df_temp2.head()

   id_comarca comarca_tjsp_temp
0     3500105        adamantina
1     3500105        adamantina
2     3500105        adamantina
3     3500303             aguai
4     3500709            agudos

In [15]:
# Merge
df_temp3 = pd.merge(
    left=df_temp,
    right=df_temp2,
    left_on="comarca_tjsp_temp",
    right_on="comarca_tjsp_temp",
    how="left",
    suffixes=["", "_copy"],
)

# Filtra Colunas
df_temp3 = df_temp3.drop(
    labels=[
        "comarca_tjsp_temp",
        "comarca_tjsp",
    ],
    axis="columns",
    errors="ignore",
)

df_temp = df_temp3[df_temp3["id_comarca"].isna()]
if len(df_temp) > 0:
    raise Exception("Erro")

# Results
df_temp3.info()
df_temp3.head()

<class 'pandas.DataFrame'>
RangeIndex: 3716 entries, 0 to 3715
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_municipio_ibge         3716 non-null   int64
 1   id_municipio_tjsp         3716 non-null   int64
 2   municipio_tjsp            3716 non-null   str
 3   municipio_tjsp_corrigido  3716 non-null   str
 4   comarca_sede              3716 non-null   int64
 5   imoveis                   3716 non-null   str
 6   id_comarca                3716 non-null   int64
dtypes: int64(4), str(3)
memory usage: 203.3 KB

,id_municipio_ibge,id_municipio_tjsp,municipio_tjsp,municipio_tjsp_corrigido,comarca_sede,imoveis,id_comarca
0,3500105,6504,Adamantina,Adamantina,1,Fórum I Adamantina,3500105
1,3500105,6504,Adamantina,Adamantina,1,Fórum I Adamantina,3500105
2,3500105,6504,Adamantina,Adamantina,1,Fórum I Adamantina,3500105
3,3500105,6504,Adamantina,Adamantina,1,Fórum II Adamantina (Residência Oficial),3500105
4,3500105,6504,Adamantina,Adamantina,1,Fórum II Adamantina (Residência Oficial),3500105

<br>

---

### Unidades

In [16]:
# Unidades
df_unidades_merge.info()
df_unidades_merge.head()

<class 'pandas.DataFrame'>
RangeIndex: 1310 entries, 0 to 1309
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_municipio_ibge         1310 non-null   int64
 1   id_municipio_tjsp         1310 non-null   int64
 2   municipio_tjsp            1310 non-null   str
 3   municipio_tjsp_corrigido  1310 non-null   str
 4   raj                       1310 non-null   str
 5   comarca_tjsp              1310 non-null   str
 6   comarca_sede              1310 non-null   int64
 7   imoveis                   1310 non-null   str
dtypes: int64(3), str(5)
memory usage: 82.0 KB

,id_municipio_ibge,id_municipio_tjsp,municipio_tjsp,municipio_tjsp_corrigido,raj,comarca_tjsp,comarca_sede,imoveis
0,3500105,6504,Adamantina,Adamantina,5ª RAJ Presidente Prudente,Adamantina,1,Fórum I Adamantina
1,3500105,6504,Adamantina,Adamantina,5ª RAJ Presidente Prudente,Adamantina,1,Fórum II Adamantina (Residência Oficial)
2,3500105,6504,Adamantina,Adamantina,5ª RAJ Presidente Prudente,Adamantina,1,Fórum III Adamantina - UAAJ - FAC. ADAM. INTEG...
3,3500204,6505,Adolfo,Adolfo,8ª RAJ São José do Rio Preto,José Bonifácio,0,Fórum José Bonifácio - II (CEJUSC)
4,3500204,6505,Adolfo,Adolfo,8ª RAJ São José do Rio Preto,José Bonifácio,0,Fórum José Bonifácio I (Principal)

In [19]:
df_tjsp_unidades = df_unidades_merge[["id_municipio_ibge", "imoveis"]]
df_tjsp_unidades = df_tjsp_unidades.drop_duplicates()
df_tjsp_unidades

      id_municipio_ibge                                            imoveis
0               3500105                                 Fórum I Adamantina
1               3500105           Fórum II Adamantina (Residência Oficial)
2               3500105  Fórum III Adamantina - UAAJ - FAC. ADAM. INTEG...
3               3500204                 Fórum José Bonifácio - II (CEJUSC)
4               3500204                 Fórum José Bonifácio I (Principal)
...                 ...                                                ...
1305            3557006                                   Fórum Votorantim
1306            3557105                                Fórum Votuporanga I
1307            3557105              Fórum Votuporanga II - (Anexo Fiscal)
1308            3557105                   Fórum Votuporanga III - (CEJUSC)
1309            3557154                                     Fórum Buritama

[1306 rows x 2 columns]