<br>

# Imóveis


Por meio do _site_ [ListaTelefonica](https://www.tjsp.jus.br/ListaTelefonica) foi possível relevar as APIs que operam e fazer diversas pesquisas.

<br>

Michel Metran\
Data: 18.06.2024\
Atualizado em: 18.06.2024

In [ ]:
from tjsp_unidades import extract
from tjsp_unidades.paths import output_path_tab

In [ ]:
import pprint
import re

import pandas as pd
from bs4 import BeautifulSoup

<br>

---

## Lista de Imóveis

<br>

---

### Municípios

Inicialmente se faz necessário listar de imóveis, que está na tabela de detalhes dos municípios.

In [ ]:
# Listar Unidades
municipio = extract.Municipio()
municipio.search_batch()
municipio.detalhe_batch()

<br>

Uma vez com a função que obter os dados das Unidades e, PRINCIPALMENTE, obter as comarcas!
Foi possível iterar pelos 645 municípios para pegar as informações dos imóveis.

<br>

---

### Imóveis

In [ ]:
imovel = extract.Imovel(municipio=municipio)

<br>

Uma vez com a lista de todos os municípios e seus respectivos códigos, foi possível obter as informações dos fóruns por meio de outro método `POST`.

In [ ]:
imovel.search(termo='forum')

<br>

Há também alguns métodos privados

```python
imovel._n_caracteres_mun_max
imovel._list_termos
```

In [ ]:
imovel.search_batch()

# Results
imovel.df_search.info()
imovel.df_search.head()

<br>

Pesquisa de um imóvel qualquer

In [ ]:
mask = imovel.df_search["id_imovel"] == 240
imovel.df_search[mask]["imovel_tjsp"].values

<br>

O método `obter_imovel` reflete um _endpoint_ do TJSP que é público. Contudo, ao que tudo indicada, ele retorna o mesmo que o método `detalhe`.

In [ ]:
id_imovel = 39

In [ ]:
imovel.obter_imovel(id_imovel=id_imovel)

<br>

---

## Detalhes

É possível consultar detalhes de um imóvel

In [ ]:
imovel.detalhe(id_imovel=id_imovel)

<br>

E é possível fazer isso em modo _batch_, ou seja, pesquisando **em lote**. Para esse método eu, inicialmente, usava parte do nome das unidades (que obtive juntamente com os municípios), para pesquisar. Observei que nem todos os imóveis eram mapeados com esse método, dai "chumbei" no código a iteração entre 0 e 1200.

In [16]:
imovel.detalhe_batch()

,id_imovel,imovel,telefone,fax,email,cj,num_varas_instaladas,entrancia,comarca_tjsp,dist_capital,tensao_eletrica,endereco_lougradouro,endereco_cep,endereco_municipio,endereco_uf
0,1,Fórum I Adamantina,(18) 2106-1718,Não Informado,adamantinaadm@tjsp.jus.br,Tupã,3,Entrância Inicial,Adamantina,500.26,110V,"Avenida Ademar de Barros , 133 - Centro",17800-000,Adamantina,SP
1,2,Comarca de Aguaí,Não Informado,Não Informado,aguaiadm@tjsp.jus.br,São João da Boa Vista,1,Entrância Inicial,Aguaí,169.25,110V,"Rua Joaquim Paula Cruz , 900 - Jd. Sta. Úrsula",13863-044,Aguaí,SP
2,3,Fórum Águas de Lindóia,(19) 2154-5204,Não Informado,aguaslindoiaadm@tjsp.jus.br,Amparo,1,Entrância Inicial,Águas de Lindóia,119.20,110V,"Rua Francisco Spartani , 66 - Jd. Le Villete",13940-000,Águas de Lindóia,SP
3,4,"FÓRUM DESEMBARGADOR ""FRANCISCO MEIRELLES DOS S...",(14) 2151-5455,Não Informado,agudosadm@tjsp.jus.br,Bauru,2,Entrância Inicial,Agudos,268.95,110V,"Rua Paulo Nelli , 276 - Vila Andreotti",17120-370,Agudos,SP
4,5,"Fórum ""Desembargador ALFREDO FANUCCHI NETO""",(16) 3665-2211,Não Informado,altinopadm@tjsp.jus.br,Batatais,1,Entrância Inicial,Altinópolis,290.52,110V,"Avenida Doutor Alberto Crivelenti , 555 - Centro",14350-005,Altinópolis,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,968,Fórum Francisco Morato V - CEJUSC (Defensoria ...,(11) 4489-8701,Não Informado,Não Informado,Jundiaí,0,Entrância Final,Francisco Morato,31.60,110V,"Rua Progresso , 110 - Centro",07910-170,Francisco Morato,SP
914,969,Fórum da Barra Funda - Anexo da Infância e da ...,Não Informado,Não Informado,Não Informado,São Paulo,5,Não Informado,São Paulo,0.00,110V,"Rua José Gomes Falcão , 156 - Portão F - Barra...",01139-010,São Paulo,SP
915,970,Mairiporâ III - CEJUSC,(11) 4419-1820,Não Informado,Não Informado,Guarulhos,0,Entrância Inicial,Mairiporã,25.95,110V,"Alameda Tibiriçá , 1103 - Vila Ipanema",07600-084,Mairiporã,SP
916,971,CEJUSC II – UAAJ UNIGUARULHOS,Não Informado,Não Informado,Não Informado,Guarulhos,0,Entrância Final,Guarulhos,14.13,110V,"Praça Tereza Cristina , 88 - Centro",07023-070,Guarulhos,SP
917,972,Fórum Bauru - UPJ 1ª E 2ª VARAS DE VIOLÊNCIA D...,Não Informado,Não Informado,Não Informado,Bauru,2,Entrância Final,Bauru,283.65,110V,"Rua Silva Jardim , 2-77 - Bela Vista",17060-240,Bauru,SP

<br>

COm isso chegamos à 321 comarcas. Acredito que o erro da Vila Mimosa esteja também aqui.

In [18]:
len(set(imovel.df_detalhes['comarca_tjsp']))

321

In [22]:
mask = imovel.df_detalhes['comarca_tjsp'].str.contains('Santos')
imovel.df_detalhes[mask]

,id_imovel,imovel,telefone,fax,email,cj,num_varas_instaladas,entrancia,comarca_tjsp,dist_capital,tensao_eletrica,endereco_lougradouro,endereco_cep,endereco_municipio,endereco_uf
254,258,Fórum Santos I,(13) 3346-5782,Não Informado,admsantos@tjsp.jus.br,Santos,5,Entrância Final,Santos,55.26,220V,"Praça Patriarca José Bonifácio , s/nº - Centro",11013-190,Santos,SP
255,259,Fórum Santos II (Cível),(13) 3346-5782,Não Informado,admsantos@tjsp.jus.br,Santos,1,Entrância Final,Santos,55.26,220V,"Rua Bittencourt , 144 - Vila Nova",11013-300,Santos,SP
860,892,Fórum Santos VI - (Anexo do Juizado - UNISANTOS),Não Informado,Não Informado,Não Informado,Santos,0,Entrância Final,Santos,55.26,110V,"Rua Joaquim Nabuco , 09/11 - Vila Mathias",11015-460,Santos,SP
861,893,Fórum Santos VII - (Anexo do Juizado - UNISANTA),Não Informado,Não Informado,Não Informado,Santos,0,Entrância Final,Santos,55.26,110V,"Rua Osvaldo Cruz , 277 - Boqueirão",11045-101,Santos,SP

In [23]:
imovel.df_detalhes.to_csv(
    path_or_buf=output_path_tab / "imovel.csv",
    index=False,
)

In [24]:
df_detalhes = imovel.df_detalhes.copy()
df_detalhes.info()
df_detalhes.head()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_imovel             918 non-null    int64
 1   imovel                918 non-null    str
 2   telefone              918 non-null    str
 3   fax                   918 non-null    str
 4   email                 918 non-null    str
 5   cj                    918 non-null    str
 6   num_varas_instaladas  918 non-null    int64
 7   entrancia             918 non-null    str
 8   comarca_tjsp          918 non-null    str
 9   dist_capital          675 non-null    float64
 10  tensao_eletrica       918 non-null    str
 11  endereco_lougradouro  918 non-null    str
 12  endereco_cep          918 non-null    str
 13  endereco_municipio    918 non-null    str
 14  endereco_uf           918 non-null    str
dtypes: float64(1), int64(2), str(12)
memory usage: 107.7 KB

,id_imovel,imovel,telefone,fax,email,cj,num_varas_instaladas,entrancia,comarca_tjsp,dist_capital,tensao_eletrica,endereco_lougradouro,endereco_cep,endereco_municipio,endereco_uf
0,1,Fórum I Adamantina,(18) 2106-1718,Não Informado,adamantinaadm@tjsp.jus.br,Tupã,3,Entrância Inicial,Adamantina,500.26,110V,"Avenida Ademar de Barros , 133 - Centro",17800-000,Adamantina,SP
1,2,Comarca de Aguaí,Não Informado,Não Informado,aguaiadm@tjsp.jus.br,São João da Boa Vista,1,Entrância Inicial,Aguaí,169.25,110V,"Rua Joaquim Paula Cruz , 900 - Jd. Sta. Úrsula",13863-044,Aguaí,SP
2,3,Fórum Águas de Lindóia,(19) 2154-5204,Não Informado,aguaslindoiaadm@tjsp.jus.br,Amparo,1,Entrância Inicial,Águas de Lindóia,119.20,110V,"Rua Francisco Spartani , 66 - Jd. Le Villete",13940-000,Águas de Lindóia,SP
3,4,"FÓRUM DESEMBARGADOR ""FRANCISCO MEIRELLES DOS S...",(14) 2151-5455,Não Informado,agudosadm@tjsp.jus.br,Bauru,2,Entrância Inicial,Agudos,268.95,110V,"Rua Paulo Nelli , 276 - Vila Andreotti",17120-370,Agudos,SP
4,5,"Fórum ""Desembargador ALFREDO FANUCCHI NETO""",(16) 3665-2211,Não Informado,altinopadm@tjsp.jus.br,Batatais,1,Entrância Inicial,Altinópolis,290.52,110V,"Avenida Doutor Alberto Crivelenti , 555 - Centro",14350-005,Altinópolis,SP