<br>

# Transform

In [1]:
import duckdb
import pandas as pd

from tjsp_unidades import extract
from tjsp_unidades.transform.small_functions import adjust_columns

<br>

---

## Get Data

<br>

---

### Quem Somos

In [2]:
quem_somos = extract.QuemSomos()

In [5]:
quem_somos.rajs.head(2)

,id_raj,raj_nome,raj_sigla,raj_regiao,juiz_diretor_nome,juiz_diretor_email
0,1,1ª RAJ - Grande São Paulo,1ª RAJ,Grande São Paulo,Fernando Antonio Tasso,daraj1@tjsp.jus.br
1,2,2ª RAJ - Araçatuba,2ª RAJ,Araçatuba,Antonio Fernando Sanches Batagelo,daraj2@tjsp.jus.br

In [6]:
quem_somos.cjs.head(2)

   id_cj cj_sigla                      cj_nome  id_raj
0      0  Capital                      Capital       1
1      1    1ª CJ  1ª Circunscrição Judiciária       7

In [7]:
quem_somos.comarcas.head(2)

  comarca_tjsp  id_cj
0   Adamantina     30
1        Aguaí     50

<br>

---

### Municípios

In [8]:
municipio = extract.Municipio()

In [9]:
# Obtem todos os IDs dos Municípios do TJSP
municipio.search_batch()

# Results
municipio.df_search.info()
municipio.df_search.head()

São 4267 termos para pesquisa
<class 'pandas.DataFrame'>
RangeIndex: 645 entries, 0 to 644
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_municipio_ibge         645 non-null    int64
 1   id_municipio_tjsp         645 non-null    int64
 2   municipio_tjsp            645 non-null    str
 3   municipio_tjsp_corrigido  645 non-null    str
dtypes: int64(2), str(2)
memory usage: 20.3 KB

,id_municipio_ibge,id_municipio_tjsp,municipio_tjsp,municipio_tjsp_corrigido
0,3500105,6504,Adamantina,Adamantina
1,3500204,6505,Adolfo,Adolfo
2,3500303,6506,Aguaí,Aguaí
3,3500402,6507,Águas da Prata,Águas da Prata
4,3500501,6508,Águas de Lindóia,Águas de Lindóia

In [10]:
municipio.detalhe_batch()

# Results
municipio.df_detalhes.info()
municipio.df_detalhes.head()

<class 'pandas.DataFrame'>
Index: 1306 entries, 0 to 1309
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_municipio_tjsp  1306 non-null   int64
 1   raj                1306 non-null   str
 2   municipio_tjsp     1306 non-null   str
 3   comarca_tjsp       1306 non-null   str
 4   comarca_sede       1306 non-null   int64
 5   imovel             1306 non-null   str
dtypes: int64(2), str(4)
memory usage: 71.4 KB

,id_municipio_tjsp,raj,municipio_tjsp,comarca_tjsp,comarca_sede,imovel
0,6505,8ª RAJ São José do Rio Preto,Adolfo,José Bonifácio,0,Fórum José Bonifácio - II (CEJUSC)
1,6505,8ª RAJ São José do Rio Preto,Adolfo,José Bonifácio,0,Fórum José Bonifácio I (Principal)
2,6507,4ª RAJ Campinas,Águas da Prata,São João da Boa Vista,0,Cartório Anexo do Juizado Especial Cível - UNI...
3,6507,4ª RAJ Campinas,Águas da Prata,São João da Boa Vista,0,Fórum I Dr. Plínio Barreto
4,6508,4ª RAJ Campinas,Águas de Lindóia,Águas de Lindóia,1,Fórum Águas de Lindóia

<br>

---

### Imóveis

In [11]:
imovel = extract.Imovel(municipio=municipio)

In [12]:
imovel.search(termo='forum')

   id_imovel                                        imovel_tjsp
3          3                             Fórum Águas de Lindóia
5          4                                       Fórum Agudos
6          5                                  Fórum Altinópolis
7          6                                    Fórum Americana
9          7                          Fórum Américo Brasiliense
1        172      Fórum "Juiz Eleutério Dutra Filho" - Mongaguá
2        245  Fórum "Juiz Messias José de Melo Souza" (Sales...
4        415      Fórum Águas de Lindóia (J.E.CÍVEL e Criminal)
0        435         ANEXO FISCAL - Fórum Santa Bárbara d´Oeste
8        631                  Fórum Americana (CEJUSC) - UNISAL

In [13]:
imovel.search_batch()
imovel.df_search.info()
imovel.df_search.head(2)

São 3192 termos para pesquisa
<class 'pandas.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_imovel    640 non-null    int64
 1   imovel_tjsp  640 non-null    str
dtypes: int64(1), str(1)
memory usage: 10.1 KB

   id_imovel         imovel_tjsp
0          1  Fórum I Adamantina
1          2      Fórum de Aguaí

In [14]:
imovel.detalhe_batch()
imovel.df_detalhes.info()
imovel.df_detalhes.head(2)

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_imovel             918 non-null    int64
 1   imovel                918 non-null    str
 2   telefone              918 non-null    str
 3   fax                   918 non-null    str
 4   email                 918 non-null    str
 5   cj                    918 non-null    str
 6   num_varas_instaladas  918 non-null    int64
 7   entrancia             918 non-null    str
 8   comarca_tjsp          918 non-null    str
 9   dist_capital          675 non-null    float64
 10  tensao_eletrica       918 non-null    str
 11  endereco_lougradouro  918 non-null    str
 12  endereco_cep          918 non-null    str
 13  endereco_municipio    918 non-null    str
 14  endereco_uf           918 non-null    str
dtypes: float64(1), int64(2), str(12)
memory usage: 107.7 KB

,id_imovel,imovel,telefone,fax,email,cj,num_varas_instaladas,entrancia,comarca_tjsp,dist_capital,tensao_eletrica,endereco_lougradouro,endereco_cep,endereco_municipio,endereco_uf
0,1,Fórum I Adamantina,(18) 2106-1718,Não Informado,adamantinaadm@tjsp.jus.br,Tupã,3,Entrância Inicial,Adamantina,500.26,110V,"Avenida Ademar de Barros , 133 - Centro",17800-000,Adamantina,SP
1,2,Comarca de Aguaí,Não Informado,Não Informado,aguaiadm@tjsp.jus.br,São João da Boa Vista,1,Entrância Inicial,Aguaí,169.25,110V,"Rua Joaquim Paula Cruz , 900 - Jd. Sta. Úrsula",13863-044,Aguaí,SP

<br>

---

## Tratamento

In [15]:
con = duckdb.connect()

In [17]:
# Quem Somos
con.register("raj", quem_somos.rajs)
con.register("cj", quem_somos.cjs)
con.register("comarcas", quem_somos.comarcas)

# Município
con.register("municipio_search", municipio.df_search)
con.register("municipio_detalhes", municipio.df_detalhes)

# Imóvel
#con.register("imovel_search", imovel.df_search)
con.register("imovel_detalhes", imovel.df_detalhes)

<br>

---

### Imóveis

In [19]:
stmt = """
    SELECT
        -- Identificador
        id_imovel,
        municipio_search.id_municipio_ibge,
        municipio_search.id_municipio_tjsp,
        imovel,

        -- Contato
        telefone,
        fax,
        email,

        --cj,        
        --entrancia, -- Acho que é atributo da Comarca
        --comarca_tjsp,

        -- Atributos
        dist_capital,
        tensao_eletrica,

        -- Endereço
        endereco_lougradouro AS lougradouro,
        endereco_cep AS cep,
        --endereco_municipio,
        municipio_search.municipio_tjsp_corrigido AS municipio_tjsp_corrigido,
        endereco_uf AS uf,

        -- Setores
        num_varas_instaladas

    FROM imovel_detalhes
    LEFT JOIN municipio_search
    ON municipio_search.municipio_tjsp = imovel_detalhes.endereco_municipio

    WHERE 1=1
        -- Confiro que o JOIN é perfeito...
        --AND municipio_search.id_municipio_ibge IS NULL
"""

# Faz a consulta
df_imoveis = con.sql(stmt).df()

# Results
df_imoveis.info()
df_imoveis.head()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_imovel                 918 non-null    int64
 1   id_municipio_ibge         918 non-null    int64
 2   id_municipio_tjsp         918 non-null    int64
 3   imovel                    918 non-null    str
 4   telefone                  918 non-null    str
 5   fax                       918 non-null    str
 6   email                     918 non-null    str
 7   dist_capital              675 non-null    float64
 8   tensao_eletrica           918 non-null    str
 9   lougradouro               918 non-null    str
 10  cep                       918 non-null    str
 11  municipio_tjsp_corrigido  918 non-null    str
 12  uf                        918 non-null    str
 13  num_varas_instaladas      918 non-null    int64
dtypes: float64(1), int64(4), str(9)
memory usage: 100.5 KB

,id_imovel,id_municipio_ibge,id_municipio_tjsp,imovel,telefone,fax,email,dist_capital,tensao_eletrica,lougradouro,cep,municipio_tjsp_corrigido,uf,num_varas_instaladas
0,1,3500105,6504,Fórum I Adamantina,(18) 2106-1718,Não Informado,adamantinaadm@tjsp.jus.br,500.26,110V,"Avenida Ademar de Barros , 133 - Centro",17800-000,Adamantina,SP,3
1,2,3500303,6506,Comarca de Aguaí,Não Informado,Não Informado,aguaiadm@tjsp.jus.br,169.25,110V,"Rua Joaquim Paula Cruz , 900 - Jd. Sta. Úrsula",13863-044,Aguaí,SP,1
2,3,3500501,6508,Fórum Águas de Lindóia,(19) 2154-5204,Não Informado,aguaslindoiaadm@tjsp.jus.br,119.20,110V,"Rua Francisco Spartani , 66 - Jd. Le Villete",13940-000,Águas de Lindóia,SP,1
3,4,3500709,6511,"FÓRUM DESEMBARGADOR ""FRANCISCO MEIRELLES DOS S...",(14) 2151-5455,Não Informado,agudosadm@tjsp.jus.br,268.95,110V,"Rua Paulo Nelli , 276 - Vila Andreotti",17120-370,Agudos,SP,2
4,5,3501004,6515,"Fórum ""Desembargador ALFREDO FANUCCHI NETO""",(16) 3665-2211,Não Informado,altinopadm@tjsp.jus.br,290.52,110V,"Avenida Doutor Alberto Crivelenti , 555 - Centro",14350-005,Altinópolis,SP,1

<br>

---

### Comarcas e Municípios

In [23]:
stmt = """
    SELECT
        DISTINCT
        -- Identificadores
        municipio_search.id_municipio_ibge,
        municipio_detalhes.id_municipio_tjsp,
        temp.id_comarca_ibge,        

        -- Outros
        municipio_detalhes.municipio_tjsp,
        municipio_search.municipio_tjsp_corrigido,
        municipio_detalhes.comarca_tjsp,
        temp.comarca_tjsp_corrigido,
        municipio_detalhes.comarca_sede        

    FROM municipio_detalhes

    LEFT JOIN municipio_search
    ON municipio_search.id_municipio_tjsp = municipio_detalhes.id_municipio_tjsp

    LEFT JOIN (
    SELECT
        DISTINCT
        -- Identificadores
        municipio_search.id_municipio_ibge AS id_comarca_ibge,
        municipio_detalhes.comarca_tjsp,

        -- Outros
        municipio_search.municipio_tjsp_corrigido AS comarca_tjsp_corrigido

    FROM municipio_detalhes

    LEFT JOIN municipio_search
    ON municipio_search.id_municipio_tjsp = municipio_detalhes.id_municipio_tjsp

    WHERE 1=1
        AND municipio_detalhes.comarca_sede = 1
        --AND municipio_detalhes.comarca_tjsp != municipio_search.municipio_tjsp_corrigido    
    ) AS temp
    ON temp.comarca_tjsp = municipio_detalhes.comarca_tjsp

    WHERE 1=1

    ORDER BY temp.id_comarca_ibge
"""

# Faz a consulta
df_municipios = con.sql(stmt).df()


# Results
df_municipios.info()
df_municipios.head()

<class 'pandas.DataFrame'>
RangeIndex: 645 entries, 0 to 644
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_municipio_ibge         645 non-null    int64
 1   id_municipio_tjsp         645 non-null    int64
 2   id_comarca_ibge           645 non-null    int64
 3   municipio_tjsp            645 non-null    str
 4   municipio_tjsp_corrigido  645 non-null    str
 5   comarca_tjsp              645 non-null    str
 6   comarca_tjsp_corrigido    645 non-null    str
 7   comarca_sede              645 non-null    int64
dtypes: int64(4), str(4)
memory usage: 40.4 KB

,id_municipio_ibge,id_municipio_tjsp,id_comarca_ibge,municipio_tjsp,municipio_tjsp_corrigido,comarca_tjsp,comarca_tjsp_corrigido,comarca_sede
0,3528908,6829,3500105,Mariápolis,Mariápolis,Adamantina,Adamantina,0
1,3500105,6504,3500105,Adamantina,Adamantina,Adamantina,Adamantina,1
2,3500303,6506,3500303,Aguaí,Aguaí,Aguaí,Aguaí,1
3,3527009,6808,3500501,Lindóia,Lindóia,Águas de Lindóia,Águas de Lindóia,0
4,3500501,6508,3500501,Águas de Lindóia,Águas de Lindóia,Águas de Lindóia,Águas de Lindóia,1

<br>

---

### Comarcas

In [25]:
# Tabela de Comarca
stmt = """
    SELECT
        DISTINCT
        -- Identificadores
        municipio_search.id_municipio_ibge AS id_comarca_ibge,
        comarcas.id_cj,

        -- Comarca
        municipio_detalhes.comarca_tjsp,
        municipio_search.municipio_tjsp_corrigido AS comarca_tjsp_corrigido

    FROM municipio_detalhes

    LEFT JOIN municipio_search
    ON municipio_search.id_municipio_tjsp = municipio_detalhes.id_municipio_tjsp

    LEFT JOIN comarcas
    ON comarcas.comarca_tjsp = municipio_detalhes.comarca_tjsp

    WHERE 1=1
        AND municipio_detalhes.comarca_sede = 1
        --AND municipio_detalhes.comarca_tjsp != municipio_search.municipio_tjsp_corrigido

        -- Circunscrição Judiciária é Nula
        --AND comarcas.id_cj IS NULL
"""

# Faz a consulta
df_comarcas = con.sql(stmt).df()

# Results
df_comarcas.info()
df_comarcas.head()

<class 'pandas.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_comarca_ibge         320 non-null    int64
 1   id_cj                   320 non-null    int64
 2   comarca_tjsp            320 non-null    str
 3   comarca_tjsp_corrigido  320 non-null    str
dtypes: int64(2), str(2)
memory usage: 10.1 KB

   id_comarca_ibge  id_cj comarca_tjsp comarca_tjsp_corrigido
0          3506003     32        Bauru                  Bauru
1          3507407     13    Borborema              Borborema
2          3510609      4  Carapicuíba            Carapicuíba
3          3512001     14       Colina                 Colina
4          3513603     48        Cunha                  Cunha

<br>

---

### CJs

In [28]:
stmt = """
    SELECT
        *
    FROM cj
    WHERE 1=1
"""

# Faz a consulta
df_cjs = con.sql(stmt).df()

# Results
df_cjs.info()
df_cjs.head()

<class 'pandas.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id_cj     57 non-null     int64
 1   cj_sigla  57 non-null     str
 2   cj_nome   57 non-null     str
 3   id_raj    57 non-null     int64
dtypes: int64(2), str(2)
memory usage: 1.9 KB

   id_cj cj_sigla                      cj_nome  id_raj
0      0  Capital                      Capital       1
1      1    1ª CJ  1ª Circunscrição Judiciária       7
2      2    2ª CJ  2ª Circunscrição Judiciária       1
3      3    3ª CJ  3ª Circunscrição Judiciária       1
4      4    4ª CJ  4ª Circunscrição Judiciária       1

<br>

---

### RAJs

In [30]:
stmt = """
    SELECT
        *
    FROM raj
    WHERE 1=1
"""

# Faz a consulta
df_raj = con.sql(stmt).df()

# Results
df_raj.info()
df_raj.head()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_raj              10 non-null     int64
 1   raj_nome            10 non-null     str
 2   raj_sigla           10 non-null     str
 3   raj_regiao          10 non-null     str
 4   juiz_diretor_nome   10 non-null     str
 5   juiz_diretor_email  10 non-null     str
dtypes: int64(1), str(5)
memory usage: 612.0 bytes

,id_raj,raj_nome,raj_sigla,raj_regiao,juiz_diretor_nome,juiz_diretor_email
0,1,1ª RAJ - Grande São Paulo,1ª RAJ,Grande São Paulo,Fernando Antonio Tasso,daraj1@tjsp.jus.br
1,2,2ª RAJ - Araçatuba,2ª RAJ,Araçatuba,Antonio Fernando Sanches Batagelo,daraj2@tjsp.jus.br
2,3,3ª RAJ - Bauru,3ª RAJ,Bauru,Gilmar Ferraz Garmes,daraj3@tjsp.jus.br
3,4,4ª RAJ - Campinas,4ª RAJ,Campinas,Nelson Augusto Bernardes de Souza,daraj4@tjsp.jus.br
4,5,5ª RAJ - Presidente Prudente,5ª RAJ,Presidente Prudente,José Wagner Parrão Molina,daraj5@tjsp.jus.br